
[[_javascript]]
== JavaScript Library

The CometD JavaScript library is a portable JavaScript implementation with
_bindings_ for the major JavaScript toolkits, currently
http://dojotoolkit.org/[Dojo] and http://jquery.com/[jQuery].
This means that the CometD Bayeux JavaScript implementation is written in pure
JavaScript with no dependencies on the toolkits, and that the toolkit bindings
add the syntactic sugar that makes the Bayeux APIs feel like they are native
to the toolkit.
For example, it is possible to refer to the standard `cometd` object using the
following notation:

====
[source,javascript]
----
// Dojo style
var cometd = dojox.cometd;

// jQuery style
var cometd = $.cometd;
----
====

If you followed <<_primer,the primer>>, you might have noticed that the skeleton
project requires you to reference both the portable implementation, under
`org/cometd.js`, and one binding – for example Dojo's – under `dojox/cometd.js`.
For jQuery, the binding is under `jquery/jquery.cometd.js`.
The use of the Bayeux APIs from the JavaScript toolkits is almost identical, and
the following sections do not refer to a particular toolkit.
Small differences surface only when passing callback functions to the Bayeux API,
where Dojo users might use `hitch()`, while jQuery users might prefer an
anonymous function approach.

The following sections present details about the JavaScript Bayeux APIs and their
implementation secrets.

include::javascript_configure.adoc[]
include::javascript_handshake.adoc[]
include::javascript_subscribe.adoc[]
include::javascript_send.adoc[]
include::javascript_disconnect.adoc[]
include::javascript_batch.adoc[]
include::javascript_transports.adoc[]
