
[[_java_client_transports]]
==== Client Transports

You can configure `org.cometd.client.BayeuxClient` class to use multiple transports.

`BayeuxClient` currently supports transport based on HTTP (`long-polling`) and WebSocket (`websocket`).

These are the choices of transports for `long-polling`:

* `org.cometd.client.http.jetty.JettyHttpClientTransport`, based on Jetty's asynchronous https://www.eclipse.org/jetty/documentation/current/http-client.html[HttpClient]).
Maven artifact coordinates: `org.cometd.java:cometd-java-client-http-jetty`.
* `org.cometd.client.http.okhttp.OkHttpClientTransport`, based on https://square.github.io/okhttp[OkHttp], especially indicated for the use of CometD in Android.
Maven artifact coordinates: `org.cometd.java:cometd-java-client-http-okhttp`.

These are the choices of transports for `websocket`:

* `org.cometd.client.websocket.javax.WebSocketTransport`, based on https://jcp.org/en/jsr/detail?id=356[JSR 356], the standard Java WebSocket APIs.
Maven artifact coordinates: `org.cometd.java:cometd-java-client-websocket-javax`.
* `org.cometd.client.websocket.jetty.JettyWebSocketTransport`, based on Jetty's asynchronous https://www.eclipse.org/jetty/documentation/current/websocket-java.html[WebSocketClient]
Maven artifact coordinates: `org.cometd.java:cometd-java-client-websocket-jetty`.
* `org.cometd.client.websocket.okhttp.OkHttpWebSocketTransport`, based on https://square.github.io/okhttp[OkHttp] WebSocket implementation
Maven artifact coordinates: `org.cometd.java:cometd-java-client-websocket-okhttp`.

You should configure `BayeuxClient` with the `websocket` transport before the `long-polling` transport, so that `BayeuxClient` can fall back to the `long-polling` if the `websocket` transport fails.
You do so by listing the `websocket` transport before the `long-polling` transport in the `BayeuxClient` constructor:

====
[source,java,indent=0]
----
include::{doc_code}/client/ClientTransportDocs.java[tags=transports]
----
====

It is always recommended that the `websocket` transport is never used without a fallback `long-polling` transport such as `JettyHttpClientTransport`.

This is how you configure the transports based on OkHttp:

====
[source,java,indent=0]
----
include::{doc_code}/client/ClientTransportDocs.java[tags=okhttp]
----
====

===== Client Transports Configuration

The transports used by `BayeuxClient` can be configured with a number of parameters.
Below you can find the parameters that are common to all transports, and those specific for each transport.

.Client Transports Common Parameters
[cols="^2,^1,^3,<10"]
|===
| Parameter Name
| Required
| Default Value
| Parameter Description

| jsonContext
| no
| `org.cometd.common.JettyJSONContextClient`
| The `JSONContext.Client` class name (see also xref:_java_json[the JSON section])
|===

.Long Polling Client Transport Parameters
[cols="^2,^1,^3,<10"]
|===
| Parameter Name
| Required
| Default Value
| Parameter Description

| maxNetworkDelay
| no
| `HttpClient` request timeout
| The maximum number of milliseconds to wait before considering a request to the Bayeux server failed

| maxMessageSize
| no
| 1048576
| The maximum number of bytes of a HTTP response, which may contain many Bayeux messages
|===

.WebSocket Client Transport Parameters
[cols="^2,^1,^3,<10"]
|===
| Parameter Name
| Required
| Default Value
| Parameter Description

| maxNetworkDelay
| no
| 15000
| The maximum number of milliseconds to wait before considering a message to the Bayeux server failed

| connectTimeout
| no
| 30000
| The maximum number of milliseconds to wait for a WebSocket connection to be opened

| idleTimeout
| no
| 60000
| The maximum number of milliseconds a WebSocket connection is kept idle before being closed

| maxMessageSize
| no
| 8192
| The maximum number of bytes allowed for each WebSocket message (each WebSocket message
  may carry many Bayeux messages)

| stickyReconnect
| no
| true
| Whether to stick using the WebSocket transport when a WebSocket transport
  failure has been detected after the WebSocket transport was able to successfully
  connect to the server
|===
