
[[_java_server]]
=== Server Library

To run the CometD server implementation, you need to deploy a Java web application to a Servlet Container.

You configure the web application with the CometD _servlet_ that interprets the Bayeux protocol (see also xref:_java_server_configuration[the server configuration section]for the CometD servlet configuration details).

While CometD interprets Bayeux messages, applications normally implement their own business logic, so they need to be able to interact with Bayeux messages -- inspect them, modify them, publish more messages on different channels, and interact with external systems such as web services or persistent storage.

In order to implement their own business logic, applications need to write one or more user-defined services, see also xref:_java_server_services[the services section], that can act upon receiving messages on Bayeux channels.

The following sections present detailed information about the Java Server APIs and their implementation.

include::java_server_configuration.adoc[]
include::java_server_services.adoc[]
include::java_server_authorization.adoc[]
include::java_server_authentication.adoc[]
include::java_server_authorizers.adoc[]
include::java_server_transports.adoc[]
include::java_server_context.adoc[]
include::java_server_lazy_messages.adoc[]
include::java_server_multiple_sessions.adoc[]
include::java_server_jmx.adoc[]
