
[[_java_client_handshake]]
==== Handshaking

To initiate the communication with the Bayeux server, you need to call `BayeuxClient.handshake()`.

The following is a typical use:

[source,java,indent=0]
----
include::{doc_code}/client/ClientHandshakeDocs.java[tags=handshakeSetup]
----

`BayeuxClient` must be instantiated passing the absolute URL (and therefore including the scheme, host, optionally the port and the path) of the Bayeux server.
The scheme of the URL must always be either "http" or "https".
The CometD Java Client implementation will transparently take care of converting the scheme to "ws" or "wss" in case of usage of the WebSocket protocol.

Once `handshake()` has been called, you must not call `handshake()` again unless you have explicitly disconnected by calling `disconnect()`.

When `handshake()` is called, the `BayeuxClient` performs the handshake with the Bayeux server and establishes the long poll connection asynchronously.

[NOTE]
====
Calling `handshake()` _does not_ mean that you have completed the handshake with the server when `handshake()` returns.
====

To verify that the handshake is successful, you can pass a callback `MessageListener` to `BayeuxClient.handshake()`:

[source,java,indent=0]
----
include::{doc_code}/client/ClientHandshakeDocs.java[tags=callbackHandshake]
----

An alternative, equivalent, way is to add a `MessageListener` before calling `BayeuxClient.handshake()`:

[source,java,indent=0]
----
include::{doc_code}/client/ClientHandshakeDocs.java[tags=listenerHandshake]
----

Another alternative is to use the built-in synchronous features of the `BayeuxClient` and wait for the handshake to complete:

[source,java,indent=0]
----
include::{doc_code}/client/ClientHandshakeDocs.java[tags=blockingHandshake]
----

The `BayeuxClient.waitFor()` method waits the given timeout (in milliseconds)for the `BayeuxClient` to reach the given state, and returns true if the state is reached before the timeout expires.
