
[[_java_server_services_integration_spring]]
===== Services Integration with Spring

Integration of CometD services with http://springframework.org[Spring] is
particularly interesting, since most of the time your Bayeux services require
other _beans_ to perform their service.
Not all Bayeux services are as simple as the `EchoService` (see also
<<_java_server_services_inherited,the inherited services section>>, and having
Spring's dependency injection (as well as other facilities) integrated greatly
simplifies development.

[[_java_server_services_integration_spring_xml_based_spring_configuration]]
===== XML Based Spring Configuration

The `BayeuxServer` object is directly configured and initialized in the Spring
configuration file, which injects it in the servlet context, where the CometD
servlet picks it up, performing no further configuration or initialization.

The `web.xml` file is as follows:

====
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="http://java.sun.com/xml/ns/javaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd"
         version="3.0">

    <servlet>
        <servlet-name>cometd</servlet-name>
        <servlet-class>org.cometd.server.CometDServlet</servlet-class>
        <async-supported>true</async-supported>
    </servlet>
    <servlet-mapping>
        <servlet-name>cometd</servlet-name>
        <url-pattern>/cometd/*</url-pattern>
    </servlet-mapping>

    <listener>
        <listener-class>org.springframework.web.context.ContextLoaderListener</listener-class>
    </listener>

</web-app>
----
====

[IMPORTANT]
====
It is important to note that the `web.xml` above does _not_ contain any
configuration specified as `<init-param>`.
This is because if you are using Spring, you want the configuration to be
specified in just one place, that is in the Spring configuration files.

Furthermore, the `<load-on-startup>` directive is _not_ present.
Since the Servlet Specification does not define the startup order between
servlets and listeners (in particular, `<listener>` elements cannot be
ordered with a `<load-on-startup>` element), you must make sure that the
Spring `<listener>` runs before the `CometDServlet`, otherwise you risk
that two `BayeuxServer` objects are created (one by `CometDServlet` and
the other by Spring), and your application will not work properly (likely,
the connection with remote clients will be handled by the `CometDServlet`'s
`BayeuxServer`, while your services will be bound to Spring's `BayeuxServer`).

By not specifying a `<load-on-startup>` element in the `CometDServlet`
definition, the `CometDServlet` will be initialized lazily _after_ the Spring
`<listener>`, ensuring that only the Spring's `BayeuxServer` is created and
used also by `CometDServlet` when it is initialized upon receiving the first
request from remote clients.
====

Spring's `applicationContext.xml` is as follows:

====
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-4.0.xsd">

    <bean id="otherService" class="com.acme..." />

    <bean id="bayeux" class="org.cometd.server.BayeuxServerImpl" init-method="start" destroy-method="stop">
        <property name="options">
            <map>
                <entry key="timeout" value="15000" />
            </map>
        </property>
    </bean>

    <bean id="echoService" class="com.acme.cometd.EchoService">
        <constructor-arg><ref bean="bayeux" /></constructor-arg>
        <constructor-arg><ref bean="otherService" /></constructor-arg>
    </bean>

    <bean class="org.springframework.web.context.support.ServletContextAttributeExporter">
        <property name="attributes">
            <map>
                <entry key="org.cometd.bayeux" value-ref="bayeux" />
            </map>
        </property>
    </bean>
</beans>
----
====

Spring now creates the `BayeuxServer` object, configuring it via the `options`
property, initializing via the `start()` method, and exporting to the servlet
context via Spring's `ServletContextAttributeExporter`.
This ensures that `CometDServlet` will _not_ create its own instance of `BayeuxServer`,
but use the one that is already present in the servlet context, created by Spring.

Below you can find a Spring's `applicationContext.xml` that configures the `BayeuxServer`
object with the WebSocket transport:

====
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-4.0.xsd">

    <bean id="bayeux" class="org.cometd.server.BayeuxServerImpl" init-method="start" destroy-method="stop">
        <property name="transports">
            <list>
                <bean id="websocketTransport" class="org.cometd.websocket.server.WebSocketTransport">
                    <constructor-arg ref="bayeux" />
                </bean>
                <bean id="jsonTransport" class="org.cometd.server.transport.JSONTransport">
                    <constructor-arg ref="bayeux" />
                </bean>
                <bean id="jsonpTransport" class="org.cometd.server.transport.JSONPTransport">
                    <constructor-arg ref="bayeux" />
                </bean>
            </list>
        </property>
    </bean>

    ... as before ...

</beans>
----
====

[NOTE]
====
When configuring the `BayeuxServer` transports, you need to explicitly
specify all the transports you want, included the default transports that you
do not need to specify when configuring a `BayeuxServer` using the `CometDServlet`.
The order of the transports is important, and you want the `WebSocketTransport`
to be the first of the list, followed by at least the `JSONTransport` (also
known as the "long-polling" transport) as a fallback.
====

===== Annotation Based Spring Configuration

Spring 3 or greater supports annotation-based configuration, and
<<_java_server_services_annotated,the annotated services section>> integrate
nicely with Spring, version 3 or greater.
Spring 3 or greater is required because it supports injection via
http://jcp.org/en/jsr/detail?id=330[JSR 330].
Prerequisite to making Spring work with CometD annotated services is to have
JSR 330's `javax.inject` classes in the classpath along with
http://jcp.org/en/jsr/detail?id=250[JSR 250's] `javax.annotation` classes
(these are included in JDK 6 and therefore only required if you use JDK 5).

[NOTE]
====
Do not forget that Spring 3 or greater requires CGLIB classes in the classpath as well.
====

The `web.xml` file is exactly the same as the one given as an example in the
<<_java_server_services_integration_spring_xml_based_spring_configuration,XML based configuration above>>,
and the same important notes apply.

Spring's `applicationContext.xml` is as follows:

====
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-4.0.xsd
                           http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context-4.0.xsd">

    <context:component-scan base-package="com.acme..." />

</beans>
----
====

Spring scans the classpath for classes that qualify as Spring beans in the given base package.

The CometD annotated service needs some additional annotation to make it qualify as a Spring bean:

====
[source,java]
----
@javax.inject.Named // Tells Spring that this is a bean
@javax.inject.Singleton // Tells Spring that this is a singleton
@Service("echoService")
public class EchoService {
    @Inject
    private BayeuxServer bayeux;
    @Session
    private ServerSession serverSession;

    @PostConstruct
    public void init() {
        System.out.println("Echo Service Initialized");
    }

    @Listener("/echo")
    public void echo(ServerSession remote, ServerMessage.Mutable message) {
        String channel = message.getChannel();
        Object data = message.getData();
        remote.deliver(serverSession, channel, data, Promise.noop());
    }
}
----
====

The missing piece is that you need to tell Spring to perform the processing of
the CometD annotations; do so using a Spring component:

====
[source,java]
----
@Configuration
public class Configurer implements DestructionAwareBeanPostProcessor, ServletContextAware {
    private BayeuxServer bayeuxServer;
    private ServerAnnotationProcessor processor;

    @Inject
    private void setBayeuxServer(BayeuxServer bayeuxServer) {
        this.bayeuxServer = bayeuxServer;
    }

    @PostConstruct
    private void init() {
        this.processor = new ServerAnnotationProcessor(bayeuxServer);
    }

    @Override
    public Object postProcessBeforeInitialization(Object bean, String name) throws BeansException {
        processor.processDependencies(bean);
        processor.processConfigurations(bean);
        processor.processCallbacks(bean);
        return bean;
    }

    @Override
    public Object postProcessAfterInitialization(Object bean, String name) throws BeansException {
        return bean;
    }

    @Override
    public boolean requiresDestruction(Object bean) {
        return true;
    }

    @Override
    public void postProcessBeforeDestruction(Object bean, String name) throws BeansException {
        processor.deprocessCallbacks(bean);
    }

    @Bean(initMethod = "start", destroyMethod = "stop")
    public BayeuxServer bayeuxServer() {
        BayeuxServerImpl bean = new BayeuxServerImpl();
        bean.setOption(BayeuxServerImpl.LOG_LEVEL, "3");
        return bean;
    }

    @Override
    public void setServletContext(ServletContext servletContext) {
        servletContext.setAttribute(BayeuxServer.ATTRIBUTE, bayeuxServer);
    }
}
----
====

Summary:

* This Spring component is the factory for the BayeuxServer object via the
  `bayeuxServer()` method (annotated with Spring's `@Bean`).
* Creating CometD's `ServerAnnotationProcessor` requires the BayeuxServer object,
  and therefore it `@Injects` it into a setter method.
* The lifecycle callback `init()` creates CometD's `ServerAnnotationProcessor`,
  which is then used during Spring's bean post processing phases.
* Finally, the BayeuxServer object is exported into the servlet context for
  the CometD servlet to use.
