
[[_java_client_publish]]
==== Publishing

The following is a typical example of publishing a message on a channel: 

====
[source,java]
----
ClientTransport transport = ...
ClientSession client = new BayeuxClient("http://localhost:8080/cometd", transport);
client.handshake();

Map<String, Object> data = new HashMap<String, Object>();
// Fill in the data

client.getChannel("/game/table/1").publish(data);
----
====

Publishing data on a channel is an asynchronous operation. 

When the message you published arrives to the server, the server replies to
the client with a publish acknowledgment; this allows clients to be sure that
the message reached the server.
The publish acknowledgment arrives on the same channel the message was published
to, with the same message `id`, with a `successful` field.
If the message publish fails for any reason, for example because server cannot
be reached, then a publish failure will be emitted, similarly to publish acknowledgments.

In order to be notified of publish acknowledgments or failures, you can use
this variant of the `publish()` method:

====
[source,java]
----
Map<String, Object> data = new HashMap<String, Object>();
// Fill in the data

client.getChannel("/game/table/1").publish(data, new ClientSessionChannel.MessageListener()
{
    @Override
    public void onMessage(ClientSessionChannel channel, Message message)
    {
        if (message.isSuccessful())
        {
            // The message reached the server
        }
    }
});
----
====

[NOTE]
====
Calling `publish()` _does not_ mean that you have published the message when `publish()` returns.
====

Message batching is also available: 

====
[source,java]
----
final ClientSession client = ...;
client.handshake();

client.batch (new Runnable()
{
    public void run()
    {
        Map<String, Object> data1 = new HashMap<String, Object>();
        // Fill in the data1 map object
        client.getChannel("/game/table/1").publish(data1);

        Map<String, Object> data2 = new HashMap<String, Object>();
        // Fill in the data2 map object<
        client.getChannel("/game/chat/1").publish(data2);
    }
});
----
====

[WARNING]
====
The `ClientSession` API also allows you to batch using `startBatch()` and
`endBatch()`, but remember to call `endBatch()` after having called `startBatch()`,
for example in a `finally` block.
If you don't, your messages continue to queue up, and your application
does not work as expected.
====
