
[[_java_server_services_inherited]]
===== Inherited Services

A CometD inherited service is a Java class that extends the CometD class
`org.cometd.server.AbstractService`, which specifies the Bayeux channels of
interest to the service, and adheres to the contract the `AbstractService`
class defines:

====
[source,java]
----
public class EchoService extends AbstractService { <1>
    public EchoService(BayeuxServer bayeuxServer) { <2>
        super(bayeuxServer, "echo"); <3>
        addService("/echo", "processEcho"); <4>
    }

    public void processEcho(ServerSession remote, ServerMessage message) { <5>
        remote.deliver(getServerSession(), "/echo", message.getData(), Promise.noop()); <6>
    }
}
----
====

This is a simple echo service that returns the message sent by the remote
client on channel `/echo` to the remote client itself. Notice the following:

<1> Extends from `org.cometd.server.AbstractService.`
<2> Creates a constructor that takes a `org.cometd.bayeux.server.BayeuxServer` object.
<3> Calls the superclass constructor, passing the BayeuxServer object and an
    arbitrary name of the service, in this case "echo".
<4> Subscribes to channel `/echo`, and specifies the name of a method that
    must be called when a message arrives to that channel, via `addService(...)`.
<5> Defines a method with the same name specified in (4), and with an appropriate
    signature (see below).
<6> Uses the `org.cometd.bayeux.server.ServerSession` API to echo the message
    back to that particular client.

The contract that the `BayeuxService` class requires for callback methods is
that the methods must have the following signature:

====
[source,java]
----
public void processEcho(ServerSession remote, ServerMessage message)
----
====

Notice that the channel name specified in the `addService()` method may be a
wildcard, for example:

====
[source,java]
----
public class BaseballTeamService extends AbstractService {
    public BaseballTeamService(BayeuxServer bayeux) {
        super(bayeux, "baseballTeam");
        addService("/baseball/team/*", "processBaseballTeam");
    }

    public void processBaseballTeam(ServerSession remote, ServerMessage message) {
        // Upon receiving a message on channel /baseball/team/*, forward to channel /events/baseball/team/*
        getBayeux().getChannel("/events" + message.getChannel()).publish(getServerSession(), message.getData(), Promise.noop());
    }
}
----
====

Notice also how the first example uses `ServerSession.deliver(...)` to send a
message to a particular remote client, while the second uses `ServerChannel.publish(...)`
to send a message to anyone who subscribes to channel `+/events/baseball/team/*+`.

Method `addService(...)` is used to map a server-side channel listener with a
method that is invoked every time a message arrives on the channel.
It is not uncommon that a single service has multiple mappings, and mappings
may be even added and removed dynamically:

====
[source,java]
----
public class GameService extends AbstractService {
    public GameService(BayeuxServer bayeux) {
        super(bayeux, "game");
        addService("/service/game/*", "processGameCommand");
        addService("/game/event", "processGameEvent");
    }

    public void processGameCommand(ServerSession remote, ServerMessage message) {
        GameCommand command = (GameCommand)message.getData();
        switch (command.getType()) {
            case GAME_START: {
                addService("/game/" + command.getGameId(), "processGame");
                break;
            }
            case GAME_END: {
                removeService("/game/" + command.getGameId());
                break;
            }
            ...
        }
    }

    public void processGameEvent(ServerSession remote, ServerMessage message) {
        ...
    }

    public void processGame(ServerSession remote, ServerMessage message) {
        ...
    }
}
----
====

Note how mappings can be removed using method `removeService()`.

Each time a service instance is created, an associated `LocalSession` (see also
<<_concepts_sessions,this section>>) is created within the service itself: the
service is a local client.
The `LocalSession` has an associated `ServerSession` and as such it is treated
by the server in the same way a remote client (that also creates a
`ServerSession` within the server) is.
The `LocalSession` and `ServerSession` are accessible via the `AbstractService`
methods `getLocalSession()` and `getServerSession()` respectively.

[NOTE]
====
If an exception is thrown by a service method, it is caught by the CometD
implementation and logged at `INFO` level on a logger category corresponding
to the class name of the service, and no further action is taken by CometD.
====

Once you have written your Bayeux services it is time to set them up in your
web application, see either <<_java_server_services_integration,the services integration section>>
or <<_java_server_services_integration_spring,the Spring Framework services integration section>>.
