
[[_java_server_services_integration]]
===== Services Integration

There are several ways to integrate your Bayeux services into your web application.
This is complicated because the `CometDServlet` creates the BayeuxServer object, and there is no easy way to detect, in general, when the `BayeuxServer` object has been created.

===== Integration via Configuration Servlet

The simplest way to initialize your web application with your services is to use a configuration servlet.
This configuration servlet has no URL mapping because its only scope is to initialize (or _wire_ together) services for your web application to work properly.

Here is a sample `web.xml`:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="https://jakarta.ee/xml/ns/jakartaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/web-app_5_0.xsd"
         version="5.0">

  <servlet>
    <servlet-name>cometd</servlet-name>
    <servlet-class>org.cometd.server.http.jakarta.CometDServlet</servlet-class>
    <load-on-startup>1</load-on-startup>
    <async-supported>true</async-supported>
  </servlet>
  <servlet-mapping>
    <servlet-name>cometd</servlet-name>
    <url-pattern>/cometd/*</url-pattern>
  </servlet-mapping>

  <servlet>
    <servlet-name>configuration</servlet-name>
    <servlet-class>com.acme.cometd.ConfigurationServlet</servlet-class>
    <load-on-startup>2</load-on-startup>
  </servlet>

</web-app>
----

Notice that the `web.xml` file specifies `<load-on-startup>` to be:

* 1 for the CometD servlet -- so that the Bayeux object gets created and put in the `ServletContext`.
* 2 for the configuration servlet -- so that it will be initialized only after the CometD servlet has been initialized and hence the BayeuxServer object is available.

This is the code for the `ConfigurationServlet`:

[source,java,indent=0]
----
include::{doc_code}/server/ServerServiceIntegrationDocs.java[tags=configServlet]
----

See also xref:_java_server_services_inherited[this section] about the `EchoService`.

===== Integration via Configuration Listener

Instead of using a configuration servlet, you can use a configuration listener, by writing a class that implements `ServletContextAttributeListener`.

Here is a sample `web.xml` file:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="https://jakarta.ee/xml/ns/jakartaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/web-app_5_0.xsd"
         version="5.0">

  <servlet>
    <servlet-name>cometd</servlet-name>
    <servlet-class>org.cometd.server.http.jakarta.CometDServlet</servlet-class>
    <load-on-startup>1</load-on-startup>
    <async-supported>true</async-supported>
  </servlet>
  <servlet-mapping>
    <servlet-name>cometd</servlet-name>
    <url-pattern>/cometd/*</url-pattern>
  </servlet-mapping>

  <listener>
    <listener-class>com.acme.cometd.ConfigurationListener</listener-class>
  </listener>

</web-app>
----

This is the code for the `ConfigurationListener`:

[source,java,indent=0]
----
include::{doc_code}/server/ServerServiceIntegrationDocs.java[tags=configListener]
----

===== Integration of Annotated Services

If you prefer to use annotated services (see also xref:_java_server_services_annotated[the annotated services section], you still have to integrate them into your web application.
The procedure is very similar to the procedures above, but it requires use of the annotation processor to process the annotations in your services.

For example, the `ConfigurationServlet` becomes:

[source,java,indent=0]
----
include::{doc_code}/server/ServerServiceIntegrationDocs.java[tags=annotationConfigServlet]
----

===== Integration of Annotated Services via `AnnotationCometDServlet`

The `org.cometd.java.annotation.AnnotationCometDServlet` allows you to specify a comma-separated list of class names to instantiate and process using a `ServerAnnotationProcessor`.

This is a sample `web.xml`:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="https://jakarta.ee/xml/ns/jakartaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="https://jakarta.ee/xml/ns/jakartaee https://jakarta.ee/xml/ns/jakartaee/web-app_5_0.xsd"
         version="5.0">

  <servlet>
    <servlet-name>cometd</servlet-name>
    <servlet-class>org.cometd.java.annotation.AnnotationCometDServlet</servlet-class>
    <init-param>
      <param-name>services</param-name>
      <param-value>com.acme.cometd.FooService, com.acme.cometd.BarService</param-value>
    </init-param>
    <load-on-startup>1</load-on-startup>
    <async-supported>true</async-supported>
  </servlet>
  <servlet-mapping>
    <servlet-name>cometd</servlet-name>
    <url-pattern>/cometd/*</url-pattern>
  </servlet-mapping>

</web-app>
----

In this example, the `AnnotationCometDServlet` instantiates and processes the annotations of one object of class `com.acme.cometd.FooService` and of one object of class `com.acme.cometd.BarService`.

The service objects are stored as `ServletContext` attributes under their own class name, so that they can be easily retrieved by other components.

For example, `FooService` can be retrieved using the following code:

[source,java,indent=0]
----
include::{doc_code}/server/ServerServiceIntegrationDocs.java[tags=anotherServlet]
----

The services created are deprocessed when `AnnotationCometDServlet` is destroyed.
