
[[_primer]]
== Primer

=== Preparing

Working on a project that uses the CometD API requires preparation, especially regarding tools, that can save you a huge amount of time.
Each browser has its own version of the Developer Tools, where you typically have a JavaScript console tool available, a network trace tool, a CSS editor tool, etc.

The CometD project is built using https://maven.apache.org[Maven], and using Maven to also build your application is a natural fit.
This Primer uses Maven as the basis for the setup, build and run of your application, but other build tools can apply the same concepts.

[IMPORTANT]
====
.Windows Users
If you are working in the Windows OS, avoid at all costs using a path that contains spaces, such as `+C:\Document And Settings\+`, as your base path.
Use a base path such as `+C:\CometD\+` instead.
====

=== Setting Up the Project

You can set up the project in two ways: using xref:_primer_maven_way[the Maven way] or xref:_primer_non_maven_way[the non Maven way].
For both, you can follow xref:_primer_setup_details[setup section] to see how some of the files of the project are set up.

[[_primer_maven_way]]
==== The Maven Way

Setting up a project based on the CometD libraries using Maven uses the Maven _archetypes_, which create the skeleton of the project, in a style very similar to other projects scaffolding.

Issue the following command from a directory that does _not_ contain a `pom.xml` file (otherwise you will get a Maven error), for example an empty directory:

----
$ cd /tmp
$ mvn archetype:generate -Dfilter=org.cometd.archetypes:jetty11
----
----
Choose archetype:
1: remote -> org.cometd.archetypes:cometd-archetype-dojo-jetty11 (-)
2: remote -> org.cometd.archetypes:cometd-archetype-jquery-jetty11 (-)
3: remote -> org.cometd.archetypes:cometd-archetype-spring-dojo-jetty11 (-)
4: remote -> org.cometd.archetypes:cometd-archetype-spring-jquery-jetty11 (-)
Choose a number:
----

As you can see, there are four archetypes available that build a skeleton application using the Dojo or jQuery JavaScript toolkits, both with the choice of using Jetty 11 and/or Spring.
Choose Dojo with Jetty 11, which is archetype number `1`.

Next, you have to choose the version of the archetype you want to use, typically the last version of the 7.0.x series:

----
Choose org.cometd.archetypes:cometd-archetype-dojo-jetty11 version:
...
61: 7.0.0
...
----

The archetype generation requires that you define several properties and generates the application skeleton for you, for example:

----
Define value for property 'groupId': : org.cometd.primer
Define value for property 'artifactId': : dojo-jetty11-primer
Define value for property 'version':  1.0-SNAPSHOT: :
Define value for property 'package':  org.cometd.primer: :
[INFO] Using property: cometdVersion = 7.0.0
[INFO] Using property: jettyVersion = 11.0.0
[INFO] Using property: slf4jVersion = 2.0.0-alpha1
Confirm properties configuration:
groupId: org.cometd.primer
artifactId: dojo-jetty11-primer
version: 1.0-SNAPSHOT
package: org.cometd.primer
cometdVersion: 7.0.0
jettyVersion: 11.0.0
slf4jVersion: 2.0.0-alpha1
Y: :
...
[INFO] BUILD SUCCESS
----

[NOTE]
====
Do not worry for now about the Jetty version that is being used to generate
the application skeleton, since it can be easily changed afterwards.
====

Then:

----
$ cd dojo-jetty11-primer/
----

The skeleton project now exists as follows:

----
$ tree .
.
|-- pom.xml
`-- src
    `-- main
        |-- java
        |   `-- org
        |       `-- cometd
        |           `-- primer
        |               |-- CometDInitializer.java
        |               `-- HelloService.java
        `-- webapp
            |-- application.js
            |-- index.jsp
            `-- WEB-INF
                `-- web.xml
----

The skeleton project is ready for you to run using the following command:

----
$ mvn clean install
$ mvn jetty:run
----

Now point your browser at `+http://localhost:8080/dojo-jetty11-primer+`, and you should see this message:

----
CometD Connection Succeeded
Server Says: Hello, World
----

That's it.
You have already written your first CometD application :-)

If you want to use a Jetty version different from CometD's default Jetty version, you can easily do so by opening the main `pom.xml` file and modifying the value of the `jetty-version` element, for example:

.`pom.xml`
[source,xml]
----
<project ... >

    ....

    <properties>
        ...
        <jetty-version>11.0.1</jetty-version>
        ....
    </properties>

    ...

</project>
----

Then you just need to re-build and re-run the project as explained above.

[[_primer_non_maven_way]]
==== The Non-Maven Way

The first step is to configure your favorite JavaScript toolkit, in the example Dojo, that the web container must serve.
Using the Maven Way, this is obtained automatically by overlaying the CometD Dojo bindings WAR file, `cometd-javascript-dojo-<version>.war`, but here you must do it manually (the `cometd-javascript-dojo-<version>.war` is located in the `cometd-javascript/dojo/target` directory of the CometD distribution).

. Download Dojo from https://dojotoolkit.org
. Unpack the `dojo-release-<version>.tar.gz` file to a directory, for example `/tmp`, so that you have the `/tmp/dojo-release-<version>` directory, called `$DOJO` below.
. Delete the `$DOJO/dojox/cometd.js` and `$DOJO/dojox/cometd.js.uncompressed.js` files that Dojo provides (these files are empty and just stubs for the real ones that you will put in place in a moment).
. Delete the `$DOJO/dojox/cometd` directory that Dojo provides.
. Copy the `dojox/cometd.js` file of the `cometd-javascript-dojo-<version>.war` into `$DOJO/`.
. Copy the `dojox/cometd` directory of the `cometd-javascript-dojo-<version>.war` into `$DOJO/`.
  The content of the `$DOJO/dojox/cometd` directory should be the following:
+
----
dojox/cometd
|-- ack.js
|-- main.js
|-- reload.js
|-- timestamp.js
`-- timesync.js
----
. Add the `org` directory from the `cometd-javascript-dojo-<version>.war`, and all its content, at the same level of the `dojox` directory in `$DOJO/`.

The final content, equivalent to that produced by the Maven way, should be like this:

----
.
|-- dijit
|-- dojo
|-- dojox
|   |-- cometd
|   |   |-- ack.js
|   |   |-- main.js
|   |   |-- reload.js
|   |   |-- timestamp.js
|   |   `-- timesync.js
|   `-- cometd.js
|-- org
|   |-- cometd
|   |   |-- AckExtension.js
|   |   |-- ReloadExtension.js
|   |   |-- TimeStampExtension.js
|   |   `-- TimeSyncExtension.js
|   `-- cometd.js
|-- WEB-INF
|   |-- classes
|   |   `-- org
|   |       `-- cometd
|   |           `-- primer
|   |               |-- CometDInitializer.class
|   |               `-- HelloService.class
|   |-- lib
|   |   |-- cometd-java-api-server-<version>.jar
|   |   |-- cometd-java-common-<version>.jar
|   |   |-- cometd-java-server-<version>.jar
|   |   |-- cometd-java-websocket-common-server-<version>.jar
|   |   |-- cometd-java-websocket-javax-server-<version>.jar
|   |   |-- jetty-http-<version>.jar
|   |   |-- jetty-io-<version>.jar
|   |   |-- jetty-jmx-<version>.jar
|   |   |-- jetty-ee10-servlets-<version>.jar
|   |   |-- jetty-util-<version>.jar
|   |   |-- jetty-util-ajax-<version>.jar
|   |   |-- slf4j-api-<version>.jar
|   |   `-- slf4j-simple-<version>.jar
|   `-- web.xml
|-- application.js
`-- index.jsp
----

The `org` directory contains the CometD implementation and extensions, while the correspondent files in the `dojox` directory are the Dojo _bindings_.
Other bindings exist for the jQuery toolkit, but the CometD implementation is the same.

The second step is to configure the server side.
If you use Java, this means that you have to set up the CometD servlet that responds to messages from clients.
The details of the server side configuration and service development are explained in xref:_java_server[the Java server library section].

The last step is to write a JSP (or HTML) file that downloads the JavaScript dependencies and the JavaScript application, as explained in the following section.

[[_primer_setup_details]]
==== Setup Details

The JSP file, `index.jsp`, contains the reference to the JavaScript toolkit dependencies and to the JavaScript application file:

[source,html]
----
<!DOCTYPE html>
<html>
  <head>
    <script data-dojo-config="async: true, deps: ['application.js'], tlmSiblingOfDojo: true"
            src="${symbol_dollar}{pageContext.request.contextPath}/dojo/dojo.js.uncompressed.js"></script>
    <script type="text/javascript">
      var config = {
        contextPath: '${pageContext.request.contextPath}'
      };
    </script>
  </head>
<body>
  ...
</body>
</html>
----

It also configures a JavaScript configuration object, `config`, with variables that the JavaScript application might need.
This is totally optional.

The JavaScript application, contained in the `application.js` file, configures the `cometd` object and starts the application.
The archetypes provide:

[source,javascript,indent=0]
----
include::../../../../cometd-archetypes/dojo-jetty11/src/main/resources/archetype-resources/src/main/webapp/application.js[]
----

Notice the following:

* The use of the `dojo/domReady!` dependency to wait for the document to load up before executing the `cometd` object initialization.
* The use of `dojo.addOnUnload()` to disconnect when the page is refreshed or closed.
* The use of the function `+_metaHandshake()+` to set up the initial configuration on first contact with the server (or when the server has lost client information, for example because of a server restart).
  This is totally optional, but highly recommended and it is the recommended way to perform subscriptions.
* The use of the function `+_metaConnect()+` to detect when the communication has been successfully established (or re-established).
  This is totally optional, but highly recommended. +
Be warned that the use of the `+_metaConnect()+` along with the `+_connected+` status variable can result in your code (that in this simple example sets the innerHTML property) to be called more than once if, for example, you experience temporary network failures or if the server restarts. +
Therefore the code that you put in the `+_connectionEstablished()+` function must be https://en.wikipedia.org/wiki/Idempotent[idempotent].
  In other words, make sure that if the `+_connectionEstablished()+` function is called more than one time, it will behave exactly as if it is called only once.
