[appendix]
[[_release]]
== Committer Release Instructions

These instructions are only for CometD committers that want to perform a CometD release.

[[_release_test]]
=== Testing the Release

Before creating the release, the following tests should be performed:

* The xref:_installation_demos[CometD Demo] works
* The xref:_benchmarking[CometD Benchmark] works and yields good results
* The https://github.com/cometd/cometd-nodejs-client[CometD NodeJS Client] works
* The https://github.com/cometd/cometd-nodejs-server[CometD NodeJS Server] works

[[_release_create]]
=== Creating the Release

During the release process, tests are implicitly skipped to speed up the process.

----
$ mvn release:prepare
----

When asked, make sure the version control _tag_ is just the version number, for example `6.0.0`, not `cometd-project-6.0.0`.

----
$ mvn release:perform
----

When the Maven Release Plugin runs it activates the `release` profile, running sections of the `pom.xml` files that perform additional actions, such as building the distribution tarball.

As the last step, the Maven Release Plugin will run an interactive Linux shell script that performs a number of automated steps such as uploading the distribution tarball, creating and uploading the JavaDocs, copying files to dependent GitHub repositories, publishing to NPM, etc.

Below the manual steps that needs to be done to finish the release process.

[[_release_repository]]
=== Managing the Repository

Login to https://oss.sonatype.org[Sonatype OSS].

Click on "Staging Repositories" and you should see the staged project just uploaded by the `mvn release:perform` command issued above, with status "open".
Tick the checkbox correspondent to the open staged project, choose "Close", then click on the "Close" button.
This will make the staged project downloadable for testing, but not yet published to the Maven Central Repository.

Tick again the checkbox correspondent to the closed staged project, choose "Release" from the toolbar, then click on the "Release" button.
This will publish the project to the Maven Central Repository.

[[_release_issues]]
=== Close the GitHub Issues Project

Close the https://github.com/cometd/cometd/projects[GitHub Issues Project].
