
:numbered!:

[appendix]
[[_release]]
== Committer Release Instructions

These instructions are only for CometD committers that want to perform a CometD release.

[[_release_create]]
=== Creating the Release

----
$ git clone git://github.com/cometd/cometd.git release/cometd
...
$ cd release/cometd
$ mvn clean install
...
$ mvn release:prepare # Specify the tag to be just the version number
...
$ mvn release:perform -Darguments=-Dgpg.passphrase=...
...
$ git push origin master
----

[[_release_repository]]
=== Managing the Repository

Login to http://oss.sonatype.org[Sonatype OSS].

Click on "Staging Repositories" and you should see the staged project just
uploaded by the `mvn release:perform` command issued above, with status "open".
Tick the checkbox correspondent to the open staged project, choose "Close" from
the toolbar, enter a description such as "CometD Release 1.0.0", then click on
the "Close" button.
This will make the staged project downloadable for testing, but not yet published to central.

Tick again the checkbox correspondent to the closed staged project, choose "Release"
from the toolbar, enter a description such as "CometD Release 1.0.0", then click
on the "Release" button.
This will publish the project to the Maven Central Repository.

[[_release_distribution]]
=== Creating the Distribution

----
$ cd $COMETD
$ git checkout <version>
...
$ mvn clean install -DskipTests=true
...
$ cd cometd-distribution
$ mvn assembly:assembly
----

This creates the distribution tarball in the `cometd-distribution/target` directory.
Then upload it.

----
$ cd $COMETD/cometd-distribution
$ dd if=target/cometd-<version>-distribution.tar.gz | ssh <user>@download.cometd.org "sudo -u www-data dd of=/var/www/download.cometd.org/cometd-<version>-distribution.tar.gz"
----

[[_release_archetype]]
=== Upload the Archetype Catalog

Make sure the archetype catalog `$HOME/.m2/archetype-catalog.xml` refers to
the release just prepared, then upload it.

----
$ dd if=$HOME/.m2/archetype-catalog.xml | ssh <user>@cometd.org "sudo -u www-data dd of=/var/www/cometd.org/archetype-catalog.xml"
----

[[_release_docs]]
=== Create and Upload the Documentation

First, rename the documentation directory `current` to the previous release version of CometD.

----
$ ssh <user>@docs.cometd.org "sudo -u www-data mv /var/www/docs.cometd.org/current /var/www/docs.cometd.org/<previous-version>"
----

Then, build and upload the CometD Reference Manual.
This will also re-create the documentation directory `current`.

[[_release_javadocs]]
=== Create and Upload the Javadocs

----
$ cd $COMETD/cometd-java
$ mvn javadoc:aggregate-jar
$ dd if=target/cometd-java-<version>-javadoc.jar | ssh <user>@docs.cometd.org "sudo -u www-data dd of=/var/www/docs.cometd.org/current/cometd-java-<version>-javadoc.jar"
----

Then `ssh` into the host, unzip the javadocs jar file into the `apidocs` directory.

[[_release_issues]]
=== Close the GitHub Issues Milestone

Close the https://github.com/cometd/cometd/milestones[GitHub Issues Milestone].

[[_release_dojo]]
=== Update the Dojo Bindings

----
$ git clone https://github.com/cometd/cometd-dojo.git
$ cd cometd-dojo
----

Make sure that the JavaScript files are in sync with the main CometD distribution.

Edit the `package.json` file, update the CometD version and the Dojo version,
then commit it.

----
$ git push
$ git tag -a "<version>" -m "CometD Release <version>."
$ git push --tags
----

:numbered:
