
[[_support]]
== CometD Commercial Support Services

The services provided are provided directly by the CometD committers, ensuring the maximum result.

CometD training for your developers.::
  Training includes tips and tricks, experience gained by developing CometD applications over the years and much more.
Development of proof-of-concept applications.::
  We can develop these much quicker than developers not well experienced in CometD.
Development of an application framework tailored for your needs.::
  Your developers can concentrate more on the implementation of the application rather than on CometD details.
Development of custom CometD features.::
  Nothing like real-world use cases to improve an open source project like CometD.
CometD advices to your developers.::
  Your development team has direct access to CometD experts to ask questions or opinions, so that mistakes are caught early when they cost less rather than later when they will cost a lot more.
CometD applications review.::
  If you have already developed your CometD application, we can review it and suggest fixes or improvements to make it better.
CometD performance tuning.::
  If your CometD application scales only up to a certain point, we can review its performance and suggest the best changes to apply to make it scale better.
CometD clustering review.::
  If you need to scale horizontally, CometD provides a scalability cluster, see xref:_java_oort[the Oort section].
  Clustering is never easy, but we can suggest the right approach to make your application clusterable.

Any other CometD-related service that you may need, we can provide it.

https://webtide.com[Webtide] is the company that provides CometD commercial support.

https://webtide.com/contact/[Contact us] for any information you need, no obligations on your part.
