version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 50
    target-branch: "8.0.x"
    commit-message:
      prefix: "[8.0.x] "
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "jakarta.platform:jakarta.jakartaee-bom"
        versions: [ ">=11.0.0" ]
      - dependency-name: "org.eclipse.jetty:*"
        versions: [ ">=12.1.0" ]
      - dependency-name: "org.springframework:*"
        versions: [ ">=7.0.0" ]
      - dependency-name: "org.springframework.boot:*"
        versions: [ ">=4.0.0" ]

  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 50
    target-branch: "9.0.x"
    commit-message:
      prefix: "[9.0.x] "
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
